version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/smartcarpark_hourly_parking
    steps:
      - checkout
      - run:
          name: Install AWS CLI v2
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
            aws --version
      - run:
          name: Set AWS Region
          command: echo 'export AWS_REGION=ap-south-1' >> $BASH_ENV
      - run:
          name: Install dependencies
          command: npm install --production
      - run:
          name: Package Lambda function
          command: zip -r function.zip .
      - run:
          name: Remove my-layer folder if exists
          command: |
            if [ -d "my-layer" ]; then rm -rf my-layer; fi
      - run:
          name: Create Lambda Layer
          command: |
            mkdir my-layer
            cd my-layer
            mkdir nodejs
            cd nodejs
            npm init -y
            npm install <your-dependencies>
            cd ..
            zip -r my-layer.zip nodejs
            aws lambda publish-layer-version --layer-name my-layer --zip-file fileb://my-layer.zip --compatible-runtimes nodejs14.x
      - run:
          name: Deploy to AWS Lambda
          command: |
            aws lambda update-function-configuration --function-name $LAMBDA_ARN --layers arn:aws:lambda:<region>:<account-id>:layer:my-layer:<version>
            aws lambda update-function-code --function-name $LAMBDA_ARN --zip-file fileb://function.zip

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
