version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/smartcarpark_hourly_parking
    steps:
      - checkout
      - run:
          name: Install AWS CLI v2
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
            aws --version
      - run:
          name: Set AWS Region
          command: echo 'export AWS_REGION=ap-south-1' >> $BASH_ENV
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Package Lambda function
          command: zip -r function.zip .
      - run:
          name: Deploy to AWS Lambda
          command: |
            aws lambda update-function-code --function-name $LAMBDA_ARN --zip-file fileb://function.zip

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
