version: 2.1

orbs:
  node: circleci/node@4.7.0

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: npm install
      - run: npm test

  deploy:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: npm install
      - run: |
          zip -r function.zip .
          aws lambda update-function-code --function-name $LAMBDA_ARN --zip-file fileb://function.zip

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
