version: 2.1

orbs:
  node: circleci/node@4.7.0

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: npm install
      - run: npm test

  deploy:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: npm install
      - run: |
          # Install AWS CLI
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

          # Configure AWS CLI
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set aws_region $AWS_REGION

          # Zip the function
          zip -r function.zip .

          # Upload to S3
          aws s3 cp function.zip s3://circlecilambda/function.zip

          # Update Lambda function code from S3
          aws lambda update-function-code --function-name $LAMBDA_ARN --s3-bucket circlecilambda --s3-key function.zip

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
