version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Navigate to project directory
          command: cd smartcarpark_hourly_parking
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Package Lambda function
          command: zip -r function.zip .
      - run:
          name: Deploy to AWS Lambda
          command: |
            aws lambda update-function-code --function-name $LAMBDA_ARN --zip-file fileb://function.zip

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
