version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/smartcarpark_hourly_parking
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get update
            sudo apt-get install -y python3-pip
            pip3 install awscli
            aws --version
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Package Lambda function
          command: zip -r function.zip .
      - run:
          name: Deploy to AWS Lambda
          command: |
            aws lambda update-function-code --function-name $LAMBDA_ARN --zip-file fileb://function.zip

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
